### PR TITLE
requires Eclipse 4.x+, JDT

### PR DESCRIPTION
**Pull request by paulvi**

### CODE REVIEW

**Comment by hanks** [comment]
would you tell me why it requires Eclipse 4.x+, maybe I can modify 
it to be backward compatible.

**Comment by paulvi** [comment]
Why? 90% of Eclipse users use Eclipse 4.x

And then maybe in a year or 2 Eclipse 3.x API will not be supported in Eclipse 4.x.
So new software should use new Eclipse 4.x API

**Comment by hanks** [comment]
@PaulVI 
Oh, I thought there were some specified 4.x APIs in the code that will crash when running on the 
Eclipse 3.x.  So I just want to make it general and "build once to run everywhere".

If it can work on Eclipse 3.x, add [requires Eclipse 4.x+] maybe make users confused. I think just let it blank will be better.

**Comment by paulvi** [comment]
You should say that this only run in Eclipse 4.x, so that users don't try to install on 3.x

Also should be updated on Marketplace #1

**Pull request merged**
